# Generated by Django 3.1.13 on 2021-08-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('image', models.ImageField(blank=True, default='defaults/default-news.png', upload_to='posts', verbose_name='Post image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded on')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Changed on')),
                ('author', models.CharField(max_length=50, verbose_name='Post author')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
